version: 0.0

os: linux

files:
  - source: /index.html
    destination: /mywebapp/config/

hooks:

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: start_server.sh
      timeout: 300
      runas: root


 